### PR TITLE
Add "gatsby-plugin" as keyword so it'll show up in plugins search on gatsbyjs.org

### PR DESCRIPTION
**Pull request by KyleAMathews**
https://www.gatsbyjs.org/contributing/submit-to-plugin-library/

### CODE REVIEW

**Review by jmsv — APPROVED** [review]

**Comment by jmsv** [comment]
Ah, missed this. Thanks @KyleAMathews!

**Comment by jmsv** [comment]
@KyleAMathews this change has been published in [`0.4.3`](https://www.npmjs.com/package/gatsby-plugin-prettier-build/v/0.4.3) and the plugin now appears in a [search](https://www.gatsbyjs.org/plugins/?=prettier) on the plugins page, but clicking the [search result](https://www.gatsbyjs.org/packages/gatsby-plugin-prettier-build/?=prettier) lands on a "Page not found" - is there something else I need to do?

image

**Comment by KyleAMathews** [comment]
It should be up now. The page is only created when we rebuild the site

**Comment by jmsv** [comment]
Cool - up now, thanks

**Pull request merged**
